'use client';

import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traductions
const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.search': 'Rechercher',
    'nav.enterprises': 'Entreprises',
    'nav.influencers': 'Influenceurs',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'nav.dashboard': 'Tableau de bord',
    'nav.messages': 'Messagerie',
    'nav.quotes': 'Devis',
    'nav.settings': 'Paramètres',
    'nav.myQuotes': 'Mes Devis',
    'nav.myServices': 'Mes Prestations',
    'nav.searchEstablishments': 'Rechercher établissements',
    
    // Hero Section
    'hero.title': 'Boostez vos ventes avec les',
    'hero.titleHighlight': 'influenceurs qui convertissent',
    'hero.subtitle': 'influenceurs vérifiés prêts à promouvoir votre marque.',
    'hero.roi': 'ROI mesurable',
    'hero.performance': 'et performances tracées.',
    'hero.searchPlaceholder': 'Rechercher un influenceur, une catégorie...',
    'hero.searchButton': 'Rechercher',
    'hero.startButton': 'Démarrer maintenant - Gratuit',
    'hero.discoverButton': 'Voir les influenceurs',
    
    // Stats
    'stats.influencers': 'Influenceurs actifs',
    'stats.revenue': 'Chiffre d\'affaires généré',
    'stats.satisfaction': 'Taux de satisfaction',
    
    // Categories
    'categories.title': 'Découvrez vos influenceurs stars',
    'categories.subtitle': 'influenceurs premium vérifiés et prêts à',
    'categories.boost': 'booster votre marque',
    'categories.sectors': 'dans tous les secteurs.',
    'categories.neuroMarketing': 'Trouver les bonnes personnes n\'a jamais été aussi simple',
    'categories.experience': 'Après des années d\'expérience et de réseau, nous avons sélectionné les meilleurs talents pour vous.',
    
    // How it works
    'how.title': 'Votre succès en 3 étapes',
    'how.subtitle': 'Découvrez comment des milliers d\'entreprises',
    'how.multiply': 'multiplient leurs ventes',
    'how.thanks': 'grâce à nos influenceurs vérifiés.',
    
    // Steps
    'step1.title': 'Trouvez l\'influenceur parfait',
    'step1.desc': 'influenceurs vérifiés à portée de clic.',
    'step1.filter': 'Filtrez par secteur, budget, localisation et engagement pour trouver',
    'step1.partner': 'votre partenaire idéal',
    
    'step2.title': 'Collaborez en toute simplicité',
    'step2.messaging': 'Messagerie intégrée',
    'step2.tools': 'et outils de négociation',
    'step2.time': 'pour finaliser vos accords en',
    'step2.hours': 'moins de 24h',
    'step2.management': 'Gestion complète de A à Z.',
    
    'step3.title': 'Mesurez votre ROI',
    'step3.analytics': 'Analytics en temps réel',
    'step3.track': 'pour suivre l\'impact de chaque collaboration.',
    'step3.roi': 'ROI moyen +340%',
    'step3.campaigns': 'sur nos campagnes.',
    
    // Testimonials
    'testimonials.title': 'Ils transforment leur business',
    'testimonials.subtitle': 'Découvrez comment nos clients',
    'testimonials.multiply': 'multiplient leurs revenus',
    'testimonials.thanks': 'grâce à des collaborations authentiques et mesurables.',
    
    // CTA
    'cta.title': 'Prêt à exploser vos ventes ?',
    'cta.subtitle': 'entreprises nous font déjà confiance.',
    'cta.join': 'Rejoignez-les et',
    'cta.multiply': 'multipliez votre chiffre d\'affaires',
    'cta.thanks': 'grâce à des collaborations authentiques.',
    'cta.startButton': 'Démarrer maintenant - Gratuit',
    'cta.discoverButton': 'Découvrir les influenceurs',
    
    // Footer
    'footer.description': 'La plateforme de référence pour connecter les établissements aux meilleurs influenceurs.',
    'footer.enterprises': 'Entreprises',
    'footer.influencers': 'Influenceurs',
    'footer.support': 'Support',
    'footer.copyright': 'Tous droits réservés.',
    
    // Categories
    'category.food': 'Food & Lifestyle',
    'category.travel': 'Travel & Tourism',
    'category.fashion': 'Fashion & Beauty',
    'category.tech': 'Tech & Innovation',
    'category.fitness': 'Fitness & Wellness',
    'category.business': 'Business & Finance',
    
    // Additional texts
    'stats.activeInfluencers': 'Influenceurs actifs',
    'stats.revenueGenerated': 'Chiffre d\'affaires généré',
    'stats.satisfactionRate': 'Taux de satisfaction',
    'cta.revenueGenerated': 'CA généré',
    'cta.satisfaction': 'Satisfaction',
    'cta.averageROI': 'ROI moyen',
    
    // Quote page
    'quote.loading': 'Chargement du devis...',
    'quote.notFound': 'Devis introuvable',
    'quote.notFoundDesc': 'Le devis demandé n\'existe pas ou a été supprimé.',
    'quote.proposedBy': 'Devis proposé par',
    'quote.totalPrice': 'Prix total',
    'quote.projectDescription': 'Description du projet',
    'quote.deliveryTime': 'Délai de livraison',
    'quote.creationDate': 'Date de création',
    'quote.influencer': 'Influenceur',
    
    // Search page
    'search.title': 'Votre partenaire marketing idéal',
    'search.placeholder': 'Recherchez un influenceur par nom...',
    'search.city': 'Ville',
    'search.followers': 'Followers',
    'search.specialty': 'Spécialité',
    'search.age': 'Âge',
    'search.button': 'Trouver mon influenceur',
    'search.results': 'Résultats de recherche',
    'search.noResults': 'Aucun résultat trouvé',
    'search.tryAgain': 'Essayez avec d\'autres critères',
    
    // Influencer profile
    'influencer.contact': 'Contacter',
    'influencer.portfolio': 'Portfolio',
    'influencer.reviews': 'Avis clients',
    'influencer.packages': 'Packages disponibles',
    'influencer.platforms': 'Plateformes actives',
    'influencer.age': 'ans',
    'influencer.city': 'Ville',
    'influencer.audience': 'Audience',
    'influencer.followers': 'Followers',
    'influencer.selectPackage': 'Sélectionner ce package',
    'influencer.choosePackage': 'Choisir ce package',
    'influencer.popular': 'Populaire',
    'influencer.publishedOn': 'Publié le',
    
    // Navigation additional
    'nav.hotelsRestaurants': 'Hôtels & Restaurants',
    'nav.prestations': 'Prestations',
    'nav.calendar': 'Calendrier',
    'nav.stats': 'Statistiques',
    'nav.whyInfluConnect': 'Pourquoi InfluConnect',
    'nav.findInfluencers': 'Trouver des influenceurs',
    'nav.sponsorship': 'Parrainage',
    'nav.communityProgram': 'Programme communautaire',
    
    // Social platforms
    'platform.instagram': 'Instagram',
    'platform.tiktok': 'TikTok',
    'platform.youtube': 'YouTube',
    
    // Search filters
    'filter.city': 'Ville',
    'filter.followers': 'Followers',
    'filter.specialty': 'Spécialité',
    'filter.age': 'Âge',
    'filter.platform': 'Plateforme',
    'filter.micro': '1K - 10K',
    'filter.small': '10K - 100K',
    'filter.medium': '100K - 1M',
    'filter.large': '1M+',
    'filter.age18_25': '18-25 ans',
    'filter.age26_35': '26-35 ans',
    'filter.age36_45': '36-45 ans',
    'filter.age46_plus': '46+ ans',
    
    // Forgot Password
    'forgotPassword.title': 'Mot de passe oublié',
    'forgotPassword.subtitle': 'Entrez votre adresse email pour recevoir un lien de réinitialisation',
    'forgotPassword.email': 'Adresse email',
    'forgotPassword.emailPlaceholder': 'votre@email.com',
    'forgotPassword.sendButton': 'Envoyer le lien',
    'forgotPassword.sending': 'Envoi en cours...',
    'forgotPassword.backToLogin': 'Retour à la connexion',
    'forgotPassword.errors.emailRequired': 'L\'adresse email est requise',
    'forgotPassword.errors.invalidEmail': 'Adresse email invalide',
    'forgotPassword.success.title': 'Email envoyé !',
    'forgotPassword.success.description': 'Un lien de réinitialisation a été envoyé à {email}',
    'forgotPassword.success.checkSpam': 'Vérifiez votre dossier spam si vous ne recevez pas l\'email dans les prochaines minutes.',
    'forgotPassword.success.backToLogin': 'Retour à la connexion',
    
    // Reset Password
    'resetPassword.title': 'Réinitialiser le mot de passe',
    'resetPassword.subtitle': 'Choisissez un nouveau mot de passe sécurisé',
    'resetPassword.newPassword': 'Nouveau mot de passe',
    'resetPassword.confirmPassword': 'Confirmer le mot de passe',
    'resetPassword.passwordPlaceholder': 'Votre nouveau mot de passe',
    'resetPassword.confirmPasswordPlaceholder': 'Confirmez votre nouveau mot de passe',
    'resetPassword.resetButton': 'Réinitialiser le mot de passe',
    'resetPassword.resetting': 'Réinitialisation...',
    'resetPassword.backToLogin': 'Retour à la connexion',
    'resetPassword.errors.passwordRequired': 'Le mot de passe est requis',
    'resetPassword.errors.passwordTooShort': 'Le mot de passe doit contenir au moins 8 caractères',
    'resetPassword.errors.confirmPasswordRequired': 'La confirmation du mot de passe est requise',
    'resetPassword.errors.passwordsDoNotMatch': 'Les mots de passe ne correspondent pas',
    'resetPassword.requirements.title': 'Exigences du mot de passe',
    'resetPassword.requirements.minLength': 'Au moins 8 caractères',
    'resetPassword.requirements.match': 'Les mots de passe correspondent',
    'resetPassword.success.title': 'Mot de passe réinitialisé !',
    'resetPassword.success.description': 'Votre mot de passe a été mis à jour avec succès.',
    'resetPassword.success.redirect': 'Redirection vers la page de connexion...',
    'resetPassword.invalidToken.title': 'Lien invalide',
    'resetPassword.invalidToken.description': 'Ce lien de réinitialisation n\'est pas valide ou a expiré.',
    'resetPassword.invalidToken.requestNew': 'Demander un nouveau lien',
    
    // Calendar
    'calendar.title': 'Mon Calendrier',
    'calendar.subtitle': 'Gérez vos prestations et rendez-vous',
    'calendar.today': 'Aujourd\'hui',
    'calendar.october2025': 'Octobre 2025',
    'calendar.prestations': 'Prestations',
    'calendar.noPrestation': 'Aucune prestation ce jour',
    'calendar.status.confirmed': 'Confirmé',
    'calendar.status.pending': 'En attente',
    'calendar.status.completed': 'Terminé',
    'calendar.type.photo': 'Photo',
    'calendar.type.video': 'Vidéo',
    'calendar.type.event': 'Événement',
    'calendar.type.meeting': 'Réunion',
    'calendar.details': 'Détails',
    'calendar.client': 'Client',
    'calendar.date': 'Date',
    'calendar.time': 'Heure',
    'calendar.duration': 'Durée',
    'calendar.location': 'Lieu',
    'calendar.price': 'Prix',
    'calendar.description': 'Description',
    'calendar.notes': 'Notes',
    'calendar.contact': 'Contacter',
    'calendar.call': 'Appeler',
    'calendar.email': 'Email',
    'calendar.monthNames': ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    'calendar.dayNames': ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    
    // Dashboard Home
    'dashboard.welcome': 'Bienvenue',
    'dashboard.discoverOpportunities': 'Découvrez les dernières opportunités de collaboration',
    'dashboard.findOpportunities': 'Trouvez les meilleures opportunités pour votre profil',
    'dashboard.campaigns': 'Campagnes',
    'dashboard.reach': 'Portée',
    'dashboard.engagement': 'Engagement',
    'dashboard.revenue': 'Revenus',
    'dashboard.searchInfluencers': 'Découvrez vos talents',
    'dashboard.searchPlaceholder': 'Nom, catégorie, ville...',
    'dashboard.search': 'Rechercher',
    'dashboard.latestOpportunities': 'Pépites du moment',
    'dashboard.seeAll': 'Voir tout',
    'dashboard.open': 'Ouverte',
    'dashboard.closed': 'Fermée',
    'dashboard.recommendations': 'Recommandations pour vous',
    'dashboard.recommendationsDesc': 'Profils d\'influenceurs idéaux selon vos catégories',
    'dashboard.followers': 'abonnés',
    'dashboard.todo': 'À faire',
    'dashboard.messagesToRead': 'Messages à lire',
    'dashboard.quotesToValidate': 'Devis à valider',
    'dashboard.pending': 'En attente',
    'dashboard.candidaturesToValidate': 'Candidatures à valider',
    
    // Facturation
    'billing.title': 'Facturation',
    'billing.subtitle': 'Gérez toutes vos factures et prestations',
    'billing.headerTitle': 'Gérez toutes vos factures et prestations',
    'billing.headerSubtitle': 'Suivez vos paiements • Gérez votre trésorerie • Optimisez votre rentabilité',
    'billing.total': 'Total',
    'billing.paid': 'Payées',
    'billing.pending': 'En attente',
    'billing.searchPlaceholder': 'Rechercher une facture, prestation, client...',
    'billing.filterAll': 'Tous les statuts',
    'billing.filterPaid': 'Payées',
    'billing.filterPending': 'En attente',
    'billing.filterOverdue': 'En retard',
    'billing.invoice': 'Facture',
    'billing.prestation': 'Prestation',
    'billing.client': 'Client',
    'billing.influencer': 'Influenceur',
    'billing.amount': 'Montant',
    'billing.date': 'Date',
    'billing.status': 'Statut',
    'billing.actions': 'Actions',
    'billing.noInvoices': 'Aucune facture trouvée',
    'billing.view': 'Voir',
    'billing.download': 'Télécharger',
    'billing.paidStatus': 'Payée',
    'billing.pendingStatus': 'En attente',
    'billing.overdueStatus': 'En retard',
    'billing.dueDate': 'Échéance',
    'billing.noDataTitle': 'Vos premières factures arrivent bientôt !',
    'billing.noDataDesc': 'Une fois vos prestations terminées, vos factures seront générées automatiquement. Chaque facture est une étape vers la croissance de votre activité.',
    'billing.viewServices': 'Voir mes prestations',
    'billing.viewQuotes': 'Voir mes devis',
    'billing.statsWillAppear': 'Vos statistiques apparaîtront ici',
    'billing.afterFirstInvoice': 'après votre première facture',
    
    // Annonces
    'annonces.title': 'Annonces',
    'annonces.subtitle': 'Découvrez les opportunités de collaboration',
    'annonces.searchPlaceholder': 'Rechercher...',
    'annonces.filterTypes': 'Tous les types',
    'annonces.filterTypes.ets': 'Établissements',
    'annonces.filterTypes.influenceur': 'Influenceurs',
    'annonces.filterTypes.agence': 'Agences',
    'annonces.filterCategories': 'Toutes les catégories',
    'annonces.filterCities': 'Toutes les villes',
    'annonces.filterStatuses': 'Tous les statuts',
    'annonces.filterStatuses.open': 'Ouvertes',
    'annonces.filterStatuses.closed': 'Fermées',
    'annonces.filterGender': 'Tous les sexes',
    'annonces.filterGender.male': 'Hommes',
    'annonces.filterGender.female': 'Femmes',
    'annonces.filterGender.mixed': 'Mixte',
    'annonces.filterDate': 'Toutes les dates',
    'annonces.filterDate.thisWeek': 'Cette semaine',
    'annonces.filterDate.nextWeek': 'Semaine prochaine',
    'annonces.filterDate.thisMonth': 'Ce mois',
    'annonces.filterDate.nextMonth': 'Mois prochain',
    'annonces.filterDate.next3Months': '3 prochains mois',
    'annonces.filterAgeRange': 'Tous les âges',
    'annonces.filterMinPrice': 'Prix minimum',
    'annonces.filterSubCategories': 'Toutes les sous-catégories',
    'annonces.hasApplied': 'Postulé',
    'annonces.alreadyApplied': 'Déjà postulé',
    'annonces.showMoreFilters': 'Voir plus de filtres',
    'annonces.hideFilters': 'Masquer les filtres',
    'annonces.showFilters': 'Afficher les filtres',
    'annonces.noResults': 'Aucune annonce trouvée',
    'annonces.loadMore': 'Charger plus',
    'annonces.page': 'Page',
    'annonces.of': 'sur',
    'annonces.priceMinPlaceholder': 'Prix min (€)',
    'annonces.ageRanges.18-24': '18-24 ans',
    'annonces.ageRanges.25-34': '25-34 ans',
    'annonces.ageRanges.35-44': '35-44 ans',
    'annonces.ageRanges.45-54': '45-54 ans',
    'annonces.ageRanges.55-64': '55-64 ans',
    'annonces.ageRanges.65+': '65+ ans',
    
    // Mes Annonces
    'mesAnnonces.title': 'Mes Annonces',
    'mesAnnonces.subtitle': 'Gérez vos annonces et candidatures',
    'mesAnnonces.headerTitle': 'Attirez les meilleurs talents et créez des collaborations qui font la différence',
    'mesAnnonces.headerSubtitle': 'Trouvez les profils parfaits • Gérez vos annonces efficacement • Maximisez vos opportunités',
    'mesAnnonces.tab.posted': 'Mes annonces postées',
    'mesAnnonces.tab.applications': 'Mes candidatures',
    'mesAnnonces.new': 'Nouvelle annonce',
    'mesAnnonces.search': 'Rechercher par titre ou lieu...',
    'mesAnnonces.filterAll': 'Tous les statuts',
    'mesAnnonces.filterOpen': 'Ouvertes',
    'mesAnnonces.filterClosed': 'Fermées',
    'mesAnnonces.filterInProgress': 'En cours',
    'mesAnnonces.filterCompleted': 'Terminées',
    'mesAnnonces.status.open': 'Ouverte',
    'mesAnnonces.status.closed': 'Fermée',
    'mesAnnonces.status.inProgress': 'En cours',
    'mesAnnonces.status.completed': 'Terminée',
    'mesAnnonces.status.pending': 'En attente',
    'mesAnnonces.status.accepted': 'Acceptée',
    'mesAnnonces.status.rejected': 'Refusée',
    'mesAnnonces.edit': 'Modifier',
    'mesAnnonces.delete': 'Supprimer',
    'mesAnnonces.view': 'Voir',
    'mesAnnonces.viewDetails': 'Voir les détails',
    'mesAnnonces.candidatures': 'Candidatures',
    'mesAnnonces.noAnnonces': 'Aucune annonce',
    'mesAnnonces.noApplications': 'Aucune candidature',
    'mesAnnonces.stats.posted': 'Mes annonces postées',
    'mesAnnonces.stats.open': 'Ouvertes',
    'mesAnnonces.stats.closed': 'Fermées',
    'mesAnnonces.stats.applications': 'Mes candidatures',
    'mesAnnonces.noResults': 'Aucun résultat trouvé',
    'mesAnnonces.createFirst': 'Créez votre première annonce',
    'mesAnnonces.createFirstDesc': 'Commencez à publier des annonces pour attirer les meilleurs talents',
    'mesAnnonces.form.title': 'Titre de l\'annonce',
    'mesAnnonces.form.description': 'Description',
    'mesAnnonces.form.prestationType': 'Type de prestation',
    'mesAnnonces.form.influencersNumber': 'Nombre d\'influenceurs',
    'mesAnnonces.form.startDate': 'Date de début',
    'mesAnnonces.form.endDate': 'Date de fin',
    'mesAnnonces.form.location': 'Localisation',
    'mesAnnonces.form.budget': 'Budget (€)',
    'mesAnnonces.form.city': 'Ville recherchée',
    'mesAnnonces.form.searchStartDate': 'Date de début recherchée',
    'mesAnnonces.form.searchEndDate': 'Date de fin recherchée',
    'mesAnnonces.form.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer l\'annonce',
    'mesAnnonces.form.deleteWarning': 'Cette action est irréversible. Toutes les candidatures associées seront également supprimées.',
    
    // Mes Devis
    'mesDevis.title': 'Mes Devis Reçus',
    'mesDevis.subtitle': 'Gérez tous vos devis',
    'mesDevis.searchPlaceholder': 'Rechercher un devis...',
    'mesDevis.filterAll': 'Tous les statuts',
    'mesDevis.filterPending': 'En attente',
    'mesDevis.filterAccepted': 'Acceptés',
    'mesDevis.filterRejected': 'Refusés',
    'mesDevis.filterCompleted': 'Terminés',
    'mesDevis.status.pending': 'En attente',
    'mesDevis.status.accepted': 'Accepté',
    'mesDevis.status.rejected': 'Refusé',
    'mesDevis.status.completed': 'Terminé',
    'mesDevis.view': 'Voir',
    'mesDevis.accept': 'Accepter',
    'mesDevis.reject': 'Refuser',
    'mesDevis.total': 'Total',
    'mesDevis.paid': 'Payés',
    'mesDevis.pending': 'En attente',
    
    // Statistiques
    'stats.title': 'Tableau de bord Entreprise',
    'stats.subtitle': 'Suivez vos performances',
    'stats.total': 'Total',
    'stats.paid': 'Payées',
    'stats.pending': 'En attente',
    'stats.topInfluencers': 'Top Influenceurs',
    'stats.myAnnonces': 'Mes Annonces',
    'stats.availableAnnonces': 'Annonces Disponibles',
    'stats.new': 'Nouvelle',
    'stats.campaigns': 'Évolution des campagnes',
    'stats.engagement': 'Taux d\'engagement',
    'stats.revenueEvolution': 'Évolution des revenus',
    'stats.name': 'Nom',
    'stats.category': 'Catégorie',
    'stats.followers': 'Followers',
    'stats.engagementRate': 'Engagement',
    'stats.reach': 'Portée',
    'stats.growth': 'Croissance',
    
    // Prestations
    'prestations.title': 'Mes Prestations',
    'prestations.subtitle': 'Gérez vos collaborations',
    'prestations.headerTitle': 'Vos collaborations qui génèrent des résultats',
    'prestations.headerSubtitle': 'Transformez chaque collaboration en succès • Suivez l\'impact en temps réel • Maximisez votre ROI',
    'prestations.tab.upcoming': 'À venir',
    'prestations.tab.past': 'Passées',
    'prestations.new': 'Nouvelle collaboration',
    'prestations.filterAll': 'Tous',
    'prestations.filterPhoto': 'Photo',
    'prestations.filterVideo': 'Vidéo',
    'prestations.filterEvent': 'Événement',
    'prestations.filterMeeting': 'Réunion',
    'prestations.viewConversation': 'Accéder à la conversation',
    'prestations.contact': 'Contacter',
    'prestations.reschedule': 'Reprogrammer',
    'prestations.total': 'Total',
    'prestations.upcoming': 'À venir',
    'prestations.past': 'Passées',
    'prestations.inProgress': 'En cours',
    
    // Calendrier
    'calendrier.title': 'Calendrier des influenceurs',
    'calendrier.subtitle': 'Gérez vos prestations et rendez-vous',
    
    // Facturation
    'facturation.title': 'Facturation',
    'facturation.manage': 'Gérez toutes vos factures',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.all': 'Tous',
    'common.viewAll': 'Voir tout',
    'common.seeAll': 'Voir tout',
    'common.viewProfile': 'Voir le profil',
    'common.viewConversation': 'Voir toutes les conversations',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.enterprises': 'Enterprises',
    'nav.influencers': 'Influencers',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.dashboard': 'Tableau de bord',
    'nav.messages': 'Messages',
    'nav.quotes': 'Quotes',
    'nav.settings': 'Settings',
    'nav.myQuotes': 'My Quotes',
    'nav.myServices': 'My Services',
    'nav.searchEstablishments': 'Search Establishments',
    
    // Hero Section
    'hero.title': 'Boost your sales with',
    'hero.titleHighlight': 'converting influencers',
    'hero.subtitle': 'verified influencers ready to promote your brand.',
    'hero.roi': 'Measurable ROI',
    'hero.performance': 'and tracked performance.',
    'hero.searchPlaceholder': 'Search for an influencer, category...',
    'hero.searchButton': 'Search',
    'hero.startButton': 'Start now - Free',
    'hero.discoverButton': 'Discover influencers',
    
    // Stats
    'stats.influencers': 'Active influencers',
    'stats.revenue': 'Revenue generated',
    'stats.satisfaction': 'Satisfaction rate',
    
    // Categories
    'categories.title': 'Discover your star influencers',
    'categories.subtitle': 'premium verified influencers ready to',
    'categories.boost': 'boost your brand',
    'categories.sectors': 'in all sectors.',
    'categories.neuroMarketing': 'Finding the right people has never been easier',
    'categories.experience': 'After years of experience and networking, we have selected the best talents for you.',
    
    // How it works
    'how.title': 'Your success in 3 steps',
    'how.subtitle': 'Discover how thousands of companies',
    'how.multiply': 'multiply their sales',
    'how.thanks': 'thanks to our verified influencers.',
    
    // Steps
    'step1.title': 'Find the perfect influencer',
    'step1.desc': 'verified influencers at your fingertips.',
    'step1.filter': 'Filter by sector, budget, location and engagement to find',
    'step1.partner': 'your ideal partner',
    
    'step2.title': 'Collaborate with ease',
    'step2.messaging': 'Integrated messaging',
    'step2.tools': 'and negotiation tools',
    'step2.time': 'to finalize your agreements in',
    'step2.hours': 'less than 24h',
    'step2.management': 'Complete management from A to Z.',
    
    'step3.title': 'Measure your ROI',
    'step3.analytics': 'Real-time analytics',
    'step3.track': 'to track the impact of each collaboration.',
    'step3.roi': 'Average ROI +340%',
    'step3.campaigns': 'on our campaigns.',
    
    // Testimonials
    'testimonials.title': 'They transform their business',
    'testimonials.subtitle': 'Discover how our clients',
    'testimonials.multiply': 'multiply their revenue',
    'testimonials.thanks': 'thanks to authentic and measurable collaborations.',
    
    // CTA
    'cta.title': 'Ready to explode your sales?',
    'cta.subtitle': 'companies already trust us.',
    'cta.join': 'Join them and',
    'cta.multiply': 'multiply your revenue',
    'cta.thanks': 'thanks to authentic collaborations.',
    'cta.startButton': 'Start now - Free',
    'cta.discoverButton': 'Discover influencers',
    
    // Footer
    'footer.description': 'The reference platform to connect establishments with the best influencers.',
    'footer.enterprises': 'Enterprises',
    'footer.influencers': 'Influencers',
    'footer.support': 'Support',
    'footer.copyright': 'All rights reserved.',
    
    // Categories
    'category.food': 'Food & Lifestyle',
    'category.travel': 'Travel & Tourism',
    'category.fashion': 'Fashion & Beauty',
    'category.tech': 'Tech & Innovation',
    'category.fitness': 'Fitness & Wellness',
    'category.business': 'Business & Finance',
    
    // Additional texts
    'stats.activeInfluencers': 'Active influencers',
    'stats.revenueGenerated': 'Revenue generated',
    'stats.satisfactionRate': 'Satisfaction rate',
    'cta.revenueGenerated': 'Revenue generated',
    'cta.satisfaction': 'Satisfaction',
    'cta.averageROI': 'Average ROI',
    
    // Quote page
    'quote.loading': 'Loading quote...',
    'quote.notFound': 'Quote not found',
    'quote.notFoundDesc': 'The requested quote does not exist or has been deleted.',
    'quote.proposedBy': 'Quote proposed by',
    'quote.totalPrice': 'Total price',
    'quote.projectDescription': 'Project description',
    'quote.deliveryTime': 'Delivery time',
    'quote.creationDate': 'Creation date',
    'quote.influencer': 'Influencer',
    
    // Search page
    'search.title': 'Your ideal marketing partner',
    'search.placeholder': 'Search for an influencer by name...',
    'search.city': 'City',
    'search.followers': 'Followers',
    'search.specialty': 'Specialty',
    'search.age': 'Age',
    'search.button': 'Find my influencer',
    'search.results': 'Search results',
    'search.noResults': 'No results found',
    'search.tryAgain': 'Try with other criteria',
    
    // Influencer profile
    'influencer.contact': 'Contact',
    'influencer.portfolio': 'Portfolio',
    'influencer.reviews': 'Client reviews',
    'influencer.packages': 'Available packages',
    'influencer.platforms': 'Active platforms',
    'influencer.age': 'years old',
    'influencer.city': 'City',
    'influencer.audience': 'Audience',
    'influencer.followers': 'Followers',
    'influencer.selectPackage': 'Select this package',
    'influencer.choosePackage': 'Choose this package',
    'influencer.popular': 'Popular',
    'influencer.publishedOn': 'Published on',
    
    // Navigation additional
    'nav.hotelsRestaurants': 'Hotels & Restaurants',
    'nav.prestations': 'Services',
    'nav.calendar': 'Calendar',
    'nav.stats': 'Statistics',
    'nav.whyInfluConnect': 'Why InfluConnect',
    'nav.findInfluencers': 'Find influencers',
    'nav.sponsorship': 'Sponsorship',
    'nav.communityProgram': 'Community program',
    
    // Social platforms
    'platform.instagram': 'Instagram',
    'platform.tiktok': 'TikTok',
    'platform.youtube': 'YouTube',
    
    // Search filters
    'filter.city': 'City',
    'filter.followers': 'Followers',
    'filter.specialty': 'Specialty',
    'filter.age': 'Age',
    'filter.platform': 'Platform',
    'filter.micro': '1K - 10K',
    'filter.small': '10K - 100K',
    'filter.medium': '100K - 1M',
    'filter.large': '1M+',
    'filter.age18_25': '18-25 years',
    'filter.age26_35': '26-35 years',
    'filter.age36_45': '36-45 years',
    'filter.age46_plus': '46+ years',
    
    // Forgot Password
    'forgotPassword.title': 'Forgot Password',
    'forgotPassword.subtitle': 'Enter your email address to receive a reset link',
    'forgotPassword.email': 'Email address',
    'forgotPassword.emailPlaceholder': 'your@email.com',
    'forgotPassword.sendButton': 'Send reset link',
    'forgotPassword.sending': 'Sending...',
    'forgotPassword.backToLogin': 'Back to login',
    'forgotPassword.errors.emailRequired': 'Email address is required',
    'forgotPassword.errors.invalidEmail': 'Invalid email address',
    'forgotPassword.success.title': 'Email sent!',
    'forgotPassword.success.description': 'A reset link has been sent to {email}',
    'forgotPassword.success.checkSpam': 'Check your spam folder if you don\'t receive the email in the next few minutes.',
    'forgotPassword.success.backToLogin': 'Back to login',
    
    // Reset Password
    'resetPassword.title': 'Reset Password',
    'resetPassword.subtitle': 'Choose a new secure password',
    'resetPassword.newPassword': 'New password',
    'resetPassword.confirmPassword': 'Confirm password',
    'resetPassword.passwordPlaceholder': 'Your new password',
    'resetPassword.confirmPasswordPlaceholder': 'Confirm your new password',
    'resetPassword.resetButton': 'Reset password',
    'resetPassword.resetting': 'Resetting...',
    'resetPassword.backToLogin': 'Back to login',
    'resetPassword.errors.passwordRequired': 'Password is required',
    'resetPassword.errors.passwordTooShort': 'Password must be at least 8 characters',
    'resetPassword.errors.confirmPasswordRequired': 'Password confirmation is required',
    'resetPassword.errors.passwordsDoNotMatch': 'Passwords do not match',
    'resetPassword.requirements.title': 'Password requirements',
    'resetPassword.requirements.minLength': 'At least 8 characters',
    'resetPassword.requirements.match': 'Passwords match',
    'resetPassword.success.title': 'Password reset!',
    'resetPassword.success.description': 'Your password has been successfully updated.',
    'resetPassword.success.redirect': 'Redirecting to login page...',
    'resetPassword.invalidToken.title': 'Invalid link',
    'resetPassword.invalidToken.description': 'This reset link is invalid or has expired.',
    'resetPassword.invalidToken.requestNew': 'Request new link',
    
    // Calendar
    'calendar.title': 'My Calendar',
    'calendar.subtitle': 'Manage your services and appointments',
    'calendar.today': 'Today',
    'calendar.october2025': 'October 2025',
    'calendar.prestations': 'Services',
    'calendar.noPrestation': 'No service this day',
    'calendar.status.confirmed': 'Confirmed',
    'calendar.status.pending': 'Pending',
    'calendar.status.completed': 'Completed',
    'calendar.type.photo': 'Photo',
    'calendar.type.video': 'Video',
    'calendar.type.event': 'Event',
    'calendar.type.meeting': 'Meeting',
    'calendar.details': 'Details',
    'calendar.client': 'Client',
    'calendar.date': 'Date',
    'calendar.time': 'Time',
    'calendar.duration': 'Duration',
    'calendar.location': 'Location',
    'calendar.price': 'Price',
    'calendar.description': 'Description',
    'calendar.notes': 'Notes',
    'calendar.contact': 'Contact',
    'calendar.call': 'Call',
    'calendar.email': 'Email',
    'calendar.monthNames': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    'calendar.dayNames': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    
    // Dashboard Home
    'dashboard.welcome': 'Welcome',
    'dashboard.discoverOpportunities': 'Discover the latest collaboration opportunities',
    'dashboard.findOpportunities': 'Find the best opportunities for your profile',
    'dashboard.campaigns': 'Campaigns',
    'dashboard.reach': 'Reach',
    'dashboard.engagement': 'Engagement',
    'dashboard.revenue': 'Revenue',
    'dashboard.searchInfluencers': 'Search influencers',
    'dashboard.searchPlaceholder': 'Name, category, city...',
    'dashboard.search': 'Search',
    'dashboard.latestOpportunities': 'Latest opportunities',
    'dashboard.seeAll': 'See all',
    'dashboard.open': 'Open',
    'dashboard.closed': 'Closed',
    'dashboard.recommendations': 'Recommendations for you',
    'dashboard.recommendationsDesc': 'Ideal influencer profiles according to your categories',
    'dashboard.followers': 'followers',
    'dashboard.todo': 'To do',
    'dashboard.messagesToRead': 'Messages to read',
    'dashboard.quotesToValidate': 'Quotes to validate',
    'dashboard.pending': 'Pending',
    'dashboard.candidaturesToValidate': 'Applications to validate',
    
    // Facturation
    'billing.title': 'Billing',
    'billing.subtitle': 'Manage all your invoices and services',
    'billing.headerTitle': 'Manage all your invoices and services',
    'billing.headerSubtitle': 'Track your payments • Manage your cash flow • Optimize your profitability',
    'billing.total': 'Total',
    'billing.paid': 'Paid',
    'billing.pending': 'Pending',
    'billing.searchPlaceholder': 'Search invoice, service, client...',
    'billing.filterAll': 'All statuses',
    'billing.filterPaid': 'Paid',
    'billing.filterPending': 'Pending',
    'billing.filterOverdue': 'Overdue',
    'billing.invoice': 'Invoice',
    'billing.prestation': 'Service',
    'billing.client': 'Client',
    'billing.influencer': 'Influencer',
    'billing.amount': 'Amount',
    'billing.date': 'Date',
    'billing.status': 'Status',
    'billing.actions': 'Actions',
    'billing.noInvoices': 'No invoices found',
    'billing.view': 'View',
    'billing.download': 'Download',
    'billing.paidStatus': 'Paid',
    'billing.pendingStatus': 'Pending',
    'billing.overdueStatus': 'Overdue',
    'billing.dueDate': 'Due date',
    'billing.noDataTitle': 'Your first invoices are coming soon!',
    'billing.noDataDesc': 'Once your services are completed, your invoices will be generated automatically. Each invoice is a step towards the growth of your business.',
    'billing.viewServices': 'View my services',
    'billing.viewQuotes': 'View my quotes',
    'billing.statsWillAppear': 'Your statistics will appear here',
    'billing.afterFirstInvoice': 'after your first invoice',
    
    // Annonces
    'annonces.title': 'Announcements',
    'annonces.subtitle': 'Discover collaboration opportunities',
    'annonces.searchPlaceholder': 'Search...',
    'annonces.filterTypes': 'All types',
    'annonces.filterTypes.ets': 'Establishments',
    'annonces.filterTypes.influenceur': 'Influencers',
    'annonces.filterTypes.agence': 'Agencies',
    'annonces.filterCategories': 'All categories',
    'annonces.filterCities': 'All cities',
    'annonces.filterStatuses': 'All statuses',
    'annonces.filterStatuses.open': 'Open',
    'annonces.filterStatuses.closed': 'Closed',
    'annonces.filterGender': 'All genders',
    'annonces.filterGender.male': 'Male',
    'annonces.filterGender.female': 'Female',
    'annonces.filterGender.mixed': 'Mixed',
    'annonces.filterDate': 'All dates',
    'annonces.filterDate.thisWeek': 'This week',
    'annonces.filterDate.nextWeek': 'Next week',
    'annonces.filterDate.thisMonth': 'This month',
    'annonces.filterDate.nextMonth': 'Next month',
    'annonces.filterDate.next3Months': 'Next 3 months',
    'annonces.filterAgeRange': 'All ages',
    'annonces.filterMinPrice': 'Minimum price',
    'annonces.filterSubCategories': 'All sub-categories',
    'annonces.hasApplied': 'Applied',
    'annonces.alreadyApplied': 'Already applied',
    'annonces.showMoreFilters': 'Show more filters',
    'annonces.hideFilters': 'Hide filters',
    'annonces.showFilters': 'Show filters',
    'annonces.noResults': 'No announcements found',
    'annonces.loadMore': 'Load more',
    'annonces.page': 'Page',
    'annonces.of': 'of',
    'annonces.priceMinPlaceholder': 'Min price (€)',
    'annonces.ageRanges.18-24': '18-24 years',
    'annonces.ageRanges.25-34': '25-34 years',
    'annonces.ageRanges.35-44': '35-44 years',
    'annonces.ageRanges.45-54': '45-54 years',
    'annonces.ageRanges.55-64': '55-64 years',
    'annonces.ageRanges.65+': '65+ years',
    
    // Mes Annonces
    'mesAnnonces.title': 'My Announcements',
    'mesAnnonces.subtitle': 'Manage your announcements and applications',
    'mesAnnonces.headerTitle': 'Attract the best talents and create collaborations that make a difference',
    'mesAnnonces.headerSubtitle': 'Find the perfect profiles • Manage your announcements efficiently • Maximize your opportunities',
    'mesAnnonces.tab.posted': 'My posted announcements',
    'mesAnnonces.tab.applications': 'My applications',
    'mesAnnonces.new': 'New announcement',
    'mesAnnonces.search': 'Search by title or location...',
    'mesAnnonces.filterAll': 'All statuses',
    'mesAnnonces.filterOpen': 'Open',
    'mesAnnonces.filterClosed': 'Closed',
    'mesAnnonces.filterInProgress': 'In progress',
    'mesAnnonces.filterCompleted': 'Completed',
    'mesAnnonces.status.open': 'Open',
    'mesAnnonces.status.closed': 'Closed',
    'mesAnnonces.status.inProgress': 'In progress',
    'mesAnnonces.status.completed': 'Completed',
    'mesAnnonces.status.pending': 'Pending',
    'mesAnnonces.status.accepted': 'Accepted',
    'mesAnnonces.status.rejected': 'Rejected',
    'mesAnnonces.edit': 'Edit',
    'mesAnnonces.delete': 'Delete',
    'mesAnnonces.view': 'View',
    'mesAnnonces.viewDetails': 'View details',
    'mesAnnonces.candidatures': 'Applications',
    'mesAnnonces.noAnnonces': 'No announcements',
    'mesAnnonces.noApplications': 'No applications',
    'mesAnnonces.stats.posted': 'My posted announcements',
    'mesAnnonces.stats.open': 'Open',
    'mesAnnonces.stats.closed': 'Closed',
    'mesAnnonces.stats.applications': 'My applications',
    'mesAnnonces.noResults': 'No results found',
    'mesAnnonces.createFirst': 'Create your first announcement',
    'mesAnnonces.createFirstDesc': 'Start posting announcements to attract the best talents',
    'mesAnnonces.form.title': 'Announcement title',
    'mesAnnonces.form.description': 'Description',
    'mesAnnonces.form.prestationType': 'Service type',
    'mesAnnonces.form.influencersNumber': 'Number of influencers',
    'mesAnnonces.form.startDate': 'Start date',
    'mesAnnonces.form.endDate': 'End date',
    'mesAnnonces.form.location': 'Location',
    'mesAnnonces.form.budget': 'Budget (€)',
    'mesAnnonces.form.city': 'City searched',
    'mesAnnonces.form.searchStartDate': 'Search start date',
    'mesAnnonces.form.searchEndDate': 'Search end date',
    'mesAnnonces.form.deleteConfirm': 'Are you sure you want to delete the announcement',
    'mesAnnonces.form.deleteWarning': 'This action is irreversible. All associated applications will also be deleted.',
    
    // Mes Devis
    'mesDevis.title': 'My Quotes Received',
    'mesDevis.subtitle': 'Manage all your quotes',
    'mesDevis.searchPlaceholder': 'Search a quote...',
    'mesDevis.filterAll': 'All statuses',
    'mesDevis.filterPending': 'Pending',
    'mesDevis.filterAccepted': 'Accepted',
    'mesDevis.filterRejected': 'Rejected',
    'mesDevis.filterCompleted': 'Completed',
    'mesDevis.status.pending': 'Pending',
    'mesDevis.status.accepted': 'Accepted',
    'mesDevis.status.rejected': 'Rejected',
    'mesDevis.status.completed': 'Completed',
    'mesDevis.view': 'View',
    'mesDevis.accept': 'Accept',
    'mesDevis.reject': 'Reject',
    'mesDevis.total': 'Total',
    'mesDevis.paid': 'Paid',
    'mesDevis.pending': 'Pending',
    
    // Statistiques
    'stats.title': 'Tableau de bord Entreprise',
    'stats.subtitle': 'Suivez vos performances',
    'stats.total': 'Total',
    'stats.paid': 'Payées',
    'stats.pending': 'En attente',
    'stats.topInfluencers': 'Top Influenceurs',
    'stats.myAnnonces': 'Mes Annonces',
    'stats.availableAnnonces': 'Annonces Disponibles',
    'stats.new': 'Nouvelle',
    'stats.campaigns': 'Évolution des campagnes',
    'stats.engagement': 'Taux d\'engagement',
    'stats.revenueEvolution': 'Évolution des revenus',
    'stats.name': 'Nom',
    'stats.category': 'Catégorie',
    'stats.followers': 'Followers',
    'stats.engagementRate': 'Engagement',
    'stats.reach': 'Portée',
    'stats.growth': 'Croissance',
    
    // Prestations
    'prestations.title': 'Mes Prestations',
    'prestations.subtitle': 'Gérez vos collaborations',
    'prestations.headerTitle': 'Vos collaborations qui génèrent des résultats',
    'prestations.headerSubtitle': 'Transformez chaque collaboration en succès • Suivez l\'impact en temps réel • Maximisez votre ROI',
    'prestations.tab.upcoming': 'À venir',
    'prestations.tab.past': 'Passées',
    'prestations.new': 'Nouvelle collaboration',
    'prestations.filterAll': 'Tous',
    'prestations.filterPhoto': 'Photo',
    'prestations.filterVideo': 'Vidéo',
    'prestations.filterEvent': 'Événement',
    'prestations.filterMeeting': 'Réunion',
    'prestations.viewConversation': 'Accéder à la conversation',
    'prestations.contact': 'Contacter',
    'prestations.reschedule': 'Reprogrammer',
    'prestations.total': 'Total',
    'prestations.upcoming': 'À venir',
    'prestations.past': 'Passées',
    'prestations.inProgress': 'En cours',
    
    // Calendrier
    'calendrier.title': 'Calendrier des influenceurs',
    'calendrier.subtitle': 'Gérez vos prestations et rendez-vous',
    
    // Facturation
    'facturation.title': 'Facturation',
    'facturation.manage': 'Gérez toutes vos factures',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.all': 'Tous',
    'common.viewAll': 'Voir tout',
    'common.seeAll': 'Voir tout',
    'common.viewProfile': 'Voir le profil',
    'common.viewConversation': 'Voir toutes les conversations',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      return (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'en')) ? savedLanguage : 'fr';
    }
    return 'fr';
  });

  // Sauvegarder la langue dans le localStorage
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const value = translations[language][key as keyof typeof translations[typeof language]];
    if (Array.isArray(value)) {
      return value.join(', ');
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
